name: find_pros
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^8.1.4
  get: ^4.6.6
  gap: ^3.0.1
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.11
  scroll_indicator: ^0.0.3
  carousel_slider: ^5.0.0
  flutter_rating_stars: ^1.1.0
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  geolocator: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:



  uses-material-design: true

  assets:
    - assets/
    - assets/logos/
    - assets/icons/